package com.example.prompt_template_demo.service.chat;

import java.util.HashMap;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.messages.SystemMessage;
import org.springframework.ai.chat.messages.UserMessage;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.chat.prompt.PromptTemplate;
import org.springframework.ai.chat.prompt.SystemPromptTemplate;
import org.springframework.stereotype.Service;

import com.example.prompt_template_demo.repo.AccountRepo;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import reactor.core.publisher.Flux;

@Service
@RequiredArgsConstructor
@Slf4j
public class ChatServiceImpl implements ChatService {
  private final ChatClient chatClient;
  private final AccountRepo accountRepo;

  @Override
  public Flux<String> talkToLlm(String message) {
    // System Message
    var systemTemplate = """
        You are a Bank Assistant.

        Guidelines:
        - You will be provided user's account details which are necessary.
        - You can help the user ONLY with account details.
        - If the user asks something unrelated to Bank Account Details Teller, simply reply:
            - Sorry, I can't help you with this
        - Do not generate any code.

        Output Format:
        - Use Markdown for formatting.
        - Use the account details that are provided to you. Don't make up things.
        - If any necessary information is missing then simply reply: "Sorry for the incovience, I can't help you this time."
        - Greet the user in Indian style with their name:
        - Namaste <name>, welcome to your account details.
        - Add a short funny remark generated by the model in Indian context.
        - Do NOT display the complete account number.
        - Mask the account number.
        - Display account balance as: Account Balance: ₹ <balance>
        - Balance must be shown with two decimal places.
        """;

    var sysPt = SystemPromptTemplate.builder()
        .template(systemTemplate)
        .build();

    // User Message
    var userTemplate = """
        User Query: {query}
        User's account details: {accountDetails}
        """;

    var params = new HashMap<String, Object>();
    params.put("query", message);
    params.put("accountDetails", accountRepo.getAccountDetails());

    var userPt = PromptTemplate.builder()
        .template(userTemplate)
        .variables(params)
        .build();

    // For System -> System Message
    var systemMessage = SystemMessage.builder()
        .text(sysPt.render())
        .build();

    // For User -> User Message
    var userMessage = UserMessage.builder()
        .text(userPt.render())
        .build();

    log.info("System Message: {}", systemMessage);
    log.info("User Message: {}", userMessage);

    Prompt prompt = Prompt.builder()
        .messages(systemMessage, userMessage)
        .build();

    return chatClient
        .prompt(prompt)
        .stream()
        .content();
  }

}
